$('.owl-carousel').owlCarousel({
    loop:true,
    margin:10,
    nav:false,
    responsive:{
        360:{
            items:5
        },
        700:{
            items:10
        },
        1000:{
            items:10
        }
    }
})